version: '3.8'

services:

  nginx-proxy: 
    image: nginx
    container_name: nginx-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local_network
    depends_on:
      - web
      - api

  web:
    build: 
      context: ./poupe-mais
    container_name: web
    expose:
      - "80"
    networks:
      - local_network

  api: 
    build: 
      context: ./poupe-mais-api
    container_name: api
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - local_network

  postgres:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: poupe_mais
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  postgres_data:

networks:
  local_network:
    driver: bridge