version: '3.8'

services:

  nginx-proxy:
    image: nginx:latest
    

  web:
    build: 
      context: ./poupe-mais
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - local_network

  api: 
    build: 
      context: ./poupe-mais-api
    container_name: api
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - local_network

  postgres:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: poupe_mais
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  postgres_data:

networks:
  local_network:
    driver: bridge