version: '3.8'

services:

  nginx-proxy: 
    image: nginx
    container_name: nginx-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local_network
    depends_on:
      - web
      - api

  web:
    build: 
      context: ./poupe-mais
    container_name: web
    expose:
      - "80"
    networks:
      - local_network

  api: 
    build: 
      context: ./poupe-mais-api
    container_name: api
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - local_network

  postgres:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  postgres_data:

networks:
  local_network:
    driver: bridge